spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/master
    username: zieltech
    password: zieltech
    driverClassName: org.postgresql.Driver